name: Build and Release Executables

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: linux
          - os: windows-latest
            target: windows

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # Specify Go 1.22 explicitly

      # Build the executable
      - name: Build executable
        run: |
          GOOS=${{ matrix.target }} GOARCH=amd64 go build -o dumb-grep-${{ matrix.target }}

      # Upload executables to release
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/')
        with:
          files: dumb-grep-${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
