name: Build and Release Executables

on:
  push:
    tags:          # Trigger workflow only on tagged commits
      - 'v*'       # Match tags like v1.0, v1.1, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: linux
          - os: windows-latest
            target: windows

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # Specify Go version

      # Build the executable
      - name: Build executable
        run: |
          if [ "${{ matrix.target }}" = "windows" ]; then
            GOOS=windows GOARCH=amd64 go build -o dumb-grep-${{ matrix.target }}.exe
          else
            GOOS=${{ matrix.target }} GOARCH=amd64 go build -o dumb-grep-${{ matrix.target }}
          fi

      # Upload executables to release
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dumb-grep-linux
            dumb-grep-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
